language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

sudo: true

services:
  - docker

env:
  global:
    - TEST_COMMAND="composer test"
    - AMP_DEBUG=true

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 7.2
      env: COVERAGE=true TEST_COMMAND="composer test-coverage"
    - php: 7.2
      env: TEST_COMMAND="composer lint"

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure --disable-dependency-tracking
  - make
  - sudo make install
  - sudo /sbin/ldconfig
  - cd ..
  - rm -fr libsodium
  - pecl install libsodium
install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - if [[ $COVERAGE = true ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar; fi
  - if [[ $COVERAGE = true ]]; then chmod +x coveralls.phar; fi
  - docker build -t ssh .
  - docker run -d -ti -p 2222:22 ssh

script:
  - composer validate --strict --no-check-lock
  - $TEST_COMMAND

after_script:
  - cat debug.log
  - if [[ $COVERAGE = true ]]; then ./coveralls.phar -v; fi